### ISSUE TITLE
部分反馈信息乱码

### ISSUE THREAD

**Issue by asmc** [Ridter/CS_Chinese_support#1]
![image](https://user-images.githubusercontent.com/4289256/38183412-d0087394-3672-11e8-98a2-5be31a73e1b0.png)

**Comment by asmc** [comment]
期待师傅的多语言支持，
我看到这个[java编码动态识别](http://sheng.iteye.com/blog/1527012)

**Comment by Ridter** [comment]
这个问题我知道，不影响使用，所以就没改，之后有时间再改吧。

**Comment by Ridter** [comment]
代码更新了。
