### ISSUE TITLE
u forgot 1 place bro. the keystrokes la 

### ISSUE THREAD

**Issue by gaodaqiang1** [Ridter/CS_Chinese_support#7]
°Ù¶ÈÒ»ÏÂ£¬Äã¾ÍÖªµÀ - Ë®Ä¾Äê»ªµÄä¯ÀÀÆ÷
=======
ip

¹ÜÀíÔ±: ÃüÁîÌáÊ¾·û
=======
nslookup www.baidu.comn
[control][ctrl]c[up][backspace]

**Comment by Ridter** [comment]
fix.
![image](https://user-images.githubusercontent.com/6007471/45561784-240b2b00-b87b-11e8-9613-6df0d5658856.png)
